app/hr_employee/__init__.py
from flask import Blueprint
employee = Blueprint('employee', __name__)

from . import views

app/hr_employee/views.py
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required
from . import employee
from .. import db
from ..models import ResCountry,User, ResPartner, Role, HrDepartment, HrEmployee, HrJobs
from app import engine

@employee.route('/')
def index():
    emp_data = HrEmployee.query.all()
    return render_template('/hr_employee/index.html', data = emp_data)

@employee.route('/department')
def department():
    return render_template('hr_employee/departments/department.html')

@employee.route('/jobs')
def jobs():
    jobs = HrJobs.query.all()
    return render_template('hr_employee/jobs/jobs.html', data=jobs)

@employee.route('/jobs_add', methods=['GET', 'POST'])
def add_jobs():
    name = request.form.get('name')
    dept = request.form.get('dept')
    desc = request.form.get('desc')
    dept_data = HrDepartment.query.filter_by(name=dept).first()
    data = HrJobs(id=1, name=name, jobs_department=dept_data, description= desc)
    db.session.add(data)
    db.session.commit()
    flash('Data Jobs berhasil ditambah')
    return redirect(url_for('employee.jobs'))

@employee.route('/country')
def country():
    return render_template('hr_employee/country/country.html')

app/templates/hr_employee/index.html
{% extends "base_site.html" %}

{% block title %} EMPLOYEE {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <!-- top tiles -->
    <div class="">
      <div class="page-title">
        <div class="title_left">
    <!--breadcrumb -->
    <ol class="breadcrumb">
      <li><a href="/employee">Karyawan</a></li>
    </ol>
    <!--breadcrumb -->
        </div>
        <div class="title_right">
        </div>
      </div>
      <div class="x_panel">
        <div class="x_title">
          <h2><i class="fa fa-cog"></i> Opsi</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-5px, 30px, 0px);">
                <li><a class="dropdown-item" href="/employee/department">Department</a>
                </li>
                <li><a class="dropdown-item" href="/employee/jobs">Jobs</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
      
      
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Tambah Karyawan</button>
          <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="myModalLabel">Tambah</h4>
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <h4>Text in a modal</h4>
                  <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue
                    laoreet rutrum faucibus dolor auctor.</p>
                  <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl
                    consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>
      
          <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small
            modal</button> -->
          
      
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12">
          <div class="">
            <div class="x_content">
              <div class="row">
                {% for row in data %}
                <div class="col-md-3   widget widget_tally_box">
                  <div class="x_panel fixed_height_390">
                    <div class="x_content">
                      <div class="flex">
                        <!-- <ul class="list-inline widget_profile_box"> -->
                          <!-- <li>
                            <a>
                              <i class="fa fa-facebook"></i>
                            </a>
                          </li> -->
                          <!-- <li> -->
                            <img src="{{ url_for('static', filename='images/user.png') }}" alt="..." class="img-circle profile_img">
                          <!-- </li> -->
                          <!-- <li>
                            <a>
                              <i class="fa fa-twitter"></i>
                            </a>
                          </li> -->
                        <!-- </ul> -->
                      </div>
                      <h3 class="name"><a href="">{{ row.name }}</a></h3>
                      <h4 class="name">{{ row.jobs_title }}</h4>
                      <h4 class="name"><a href="{{ url_for('employee.department') }}">{{ row.departments.name }}</a></h4>
                      <div class="flex">
                        <!-- <ul class="list-inline count2">
                          <li>
                            <h3>123</h3>
                            <span>Articles</span>
                          </li> -->
                          <!-- <li> -->
                            <!-- <span>Followers</span> -->
                          <!-- </li> -->
                          <!-- <li>
                            <h3>123</h3>
                            <span>Following</span>
                          </li>
                        </ul> -->
                      </div>
                      
                    </div>
                  </div>
                </div>
                {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>    
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  <!-- Chart.js -->
  <script src="{{ url_for('static', filename='vendors/Chart.js/dist/Chart.min.js') }}"></script>
  <!-- gauge.js -->
  <script src="{{ url_for('static', filename='vendors/gauge.js/dist/gauge.min.js') }}"></script>
  <!-- Skycons -->
  <script src="{{ url_for('static', filename='vendors/skycons/skycons.js') }}"></script>
  <!-- Flot -->
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.pie.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.time.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.stack.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.resize.js') }}"></script>
  <!-- Flot plugins -->
  <script src="{{ url_for('static', filename='vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/flot.curvedlines/curvedLines.js') }}"></script>
  <!-- DateJS -->
  <script src="{{ url_for('static', filename='vendors/DateJS/build/date.js') }}"></script>
  <!-- JQVMap -->
  <script src="{{ url_for('static', filename='vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
{% endblock javascripts %}