app/hr_employee/__init__.py
from flask import Blueprint
employee = Blueprint('employee', __name__)

from . import views

app/hr_employee/views.py
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required
from . import employee
from .. import db
from ..models import ResCountry,User, ResPartner, Role, HrDepartment, HrEmployee, HrJobs
from app import engine

@employee.route('/')
def index():
    emp_data = HrEmployee.query.all()
    return render_template('/hr_employee/index.html', data = emp_data)

@employee.route('/department')
def department():
    return render_template('hr_employee/departments/department.html')

@employee.route('/jobs')
def jobs():
    jobs = HrJobs.query.all()
    return render_template('hr_employee/jobs/jobs.html', data=jobs)

@employee.route('/jobs_add', methods=['GET', 'POST'])
def add_jobs():
    name = request.form.get('name')
    dept = request.form.get('dept')
    desc = request.form.get('desc')
    dept_data = HrDepartment.query.filter_by(name=dept).first()
    data = HrJobs(id=1, name=name, jobs_department=dept_data, description= desc)
    db.session.add(data)
    db.session.commit()
    flash('Data Jobs berhasil ditambah')
    return redirect(url_for('employee.jobs'))

@employee.route('/country')
def country():
    return render_template('hr_employee/country/country.html')

app/templates/hr_employee/jobs/jobs.html
{% extends "base_site.html" %}

{% block title %} JOBS {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <!-- top tiles -->
    <div class="">
      <div class="page-title">
        <div class="title_left">
        <!--breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="/employee">Karyawan</a></li>
          <li><a href="/employee/jobs">Jobs</a></li>
        </ol>
      <!--breadcrumb -->
        </div>
        <div class="title_right">
          <div class="col-md-12">
            <!-- message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-success alert-dismissible " role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
              </button>
              <strong>Selamat!</strong> {{ message }}
            </div>
            {% endfor %}
            <!-- message -->
        </div>
      </div>
      <div class="x_panel">
        <div class="x_title">
          <h2><i class="fa fa-cog"></i> Opsi</h2>
          
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-5px, 30px, 0px);">
                <li><a class="dropdown-item" href="/employee/department">Department</a>
                </li>
                <li><a class="dropdown-item" href="/employee/jobs">Jobs</a>
                </li>
              </ul>
            </li>
            
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Tambah Jobs</button>
          <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="myModalLabel">Tambah Jobs</h4>
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="x_panel">
                    <div class="x_content">
                      <br>
                      <form method="POST" action="{{url_for('employee.add_jobs')}}" id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">
                        <div class="item form-group">
                          <label class="col-form-label col-md-3 col-sm-3 label-align" for="first-name" >Jobs Name <span
                              class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 ">
                            <input name="name" type="text" class="form-control " required="true">
                          </div>
                        </div>
                        <div class="item form-group">
                          <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">Department <span
                              class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 ">
                            <input name="dept" type="text" class="form-control" required="true">
                          </div>
                        </div>
                        <div class="item form-group">
                          <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">Description <span
                              class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 ">
                            <textarea name="desc" class="form-control" rows="3" required="true"></textarea>
                          </div>
                        </div>
                      
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <input type="submit" class="btn btn-primary"></input>
                </div>
              </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="">
            <div class="x_content">
              <div class="row">
                {% for row in data %}
                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6  ">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-group"></i>
                    </div>
                    <div class="count">{{ row.name }}</div>
                    <h3>{{ row.jobs_department.name }}</h3>
                    <p>{{ row.description }}</p>
                  </div>
                </div>
                {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


      </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  <!-- Chart.js -->
  <script src="{{ url_for('static', filename='vendors/Chart.js/dist/Chart.min.js') }}"></script>
  <!-- gauge.js -->
  <script src="{{ url_for('static', filename='vendors/gauge.js/dist/gauge.min.js') }}"></script>
  <!-- Skycons -->
  <script src="{{ url_for('static', filename='vendors/skycons/skycons.js') }}"></script>
  <!-- Flot -->
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.pie.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.time.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.stack.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.resize.js') }}"></script>
  <!-- Flot plugins -->
  <script src="{{ url_for('static', filename='vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/flot.curvedlines/curvedLines.js') }}"></script>
  <!-- DateJS -->
  <script src="{{ url_for('static', filename='vendors/DateJS/build/date.js') }}"></script>
  <!-- JQVMap -->
  <script src="{{ url_for('static', filename='vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
{% endblock javascripts %}

app/templates/hr_employee/jobs/jobs_detail.html
{% extends "base_site.html" %}

{% block title %} JOBS {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <!-- top tiles -->

    </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  <!-- Chart.js -->
  <script src="{{ url_for('static', filename='vendors/Chart.js/dist/Chart.min.js') }}"></script>
  <!-- gauge.js -->
  <script src="{{ url_for('static', filename='vendors/gauge.js/dist/gauge.min.js') }}"></script>
  <!-- Skycons -->
  <script src="{{ url_for('static', filename='vendors/skycons/skycons.js') }}"></script>
  <!-- Flot -->
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.pie.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.time.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.stack.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/Flot/jquery.flot.resize.js') }}"></script>
  <!-- Flot plugins -->
  <script src="{{ url_for('static', filename='vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/flot.curvedlines/curvedLines.js') }}"></script>
  <!-- DateJS -->
  <script src="{{ url_for('static', filename='vendors/DateJS/build/date.js') }}"></script>
  <!-- JQVMap -->
  <script src="{{ url_for('static', filename='vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
{% endblock javascripts %}